app:
  build: .
  volumes:
    - .:/opt/code
  ports:
   - "5000:5000"
  links:
   - db:postgres

db:
  restart: always
  image: postgres_db:latest
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=chrisr
    - POSTGRES_PASSWORD=chrisr
    - POSTGRES_DB=chrisr
